export interface ICountry {
  name: string;
  image?: string;
  numeric?: string;
  alpha2: string;
  alpha3?: string;
  dial?: string;
}

export const COUNTRIES: ICountry[] = [
  {
    name: 'Afghanistan',
    numeric: '004',
    alpha2: 'AF',
    alpha3: 'AFG',
    dial: '93',
  },
  {
    name: 'Åland Islands',
    numeric: '248',
    alpha2: 'AX',
    alpha3: 'ALA',
    dial: '358',
  },
  {
    name: 'Albania',
    numeric: '008',
    alpha2: 'AL',
    alpha3: 'ALB',
    dial: '355',
  },
  {
    name: 'Algeria',
    numeric: '012',
    alpha2: 'DZ',
    alpha3: 'DZA',
    dial: '213',
  },
  {
    name: 'American Samoa',
    numeric: '016',
    alpha2: 'AS',
    alpha3: 'ASM',
    dial: '1684',
  },
  {
    name: 'Andorra',
    numeric: '020',
    alpha2: 'AD',
    alpha3: 'AND',
    dial: '376',
  },
  {
    name: 'Angola',
    numeric: '024',
    alpha2: 'AO',
    alpha3: 'AGO',
    dial: '244',
  },
  {
    name: 'Anguilla',
    numeric: '660',
    alpha2: 'AI',
    alpha3: 'AIA',
    dial: '1264',
  },
  {
    name: 'Antarctica',
    numeric: '010',
    alpha2: 'AQ',
    alpha3: 'ATA',
    dial: '672',
  },
  {
    name: 'Antigua and Barbuda',
    numeric: '028',
    alpha2: 'AG',
    alpha3: 'ATG',
    dial: '1268',
  },
  {
    name: 'Argentina',
    numeric: '032',
    alpha2: 'AR',
    alpha3: 'ARG',
    dial: '54',
  },
  {
    name: 'Armenia',
    numeric: '051',
    alpha2: 'AM',
    alpha3: 'ARM',
    dial: '374',
  },
  {
    name: 'Aruba',
    numeric: '533',
    alpha2: 'AW',
    alpha3: 'ABW',
    dial: '297',
  },
  {
    name: 'Australia',
    numeric: '036',
    alpha2: 'AU',
    alpha3: 'AUS',
    dial: '61',
  },
  {
    name: 'Austria',
    numeric: '040',
    alpha2: 'AT',
    alpha3: 'AUT',
    dial: '43',
  },
  {
    name: 'Azerbaijan',
    numeric: '031',
    alpha2: 'AZ',
    alpha3: 'AZE',
    dial: '994',
  },
  {
    name: 'Bahamas',
    numeric: '044',
    alpha2: 'BS',
    alpha3: 'BHS',
    dial: '1242',
  },
  {
    name: 'Bahrain',
    numeric: '048',
    alpha2: 'BH',
    alpha3: 'BHR',
    dial: '973',
  },
  {
    name: 'Bangladesh',
    numeric: '050',
    alpha2: 'BD',
    alpha3: 'BGD',
    dial: '880',
  },
  {
    name: 'Barbados',
    numeric: '052',
    alpha2: 'BB',
    alpha3: 'BRB',
    dial: '1246',
  },
  {
    name: 'Belarus',
    numeric: '112',
    alpha2: 'BY',
    alpha3: 'BLR',
    dial: '375',
  },
  {
    name: 'Belgium',
    numeric: '056',
    alpha2: 'BE',
    alpha3: 'BEL',
    dial: '32',
  },
  {
    name: 'Belize',
    numeric: '084',
    alpha2: 'BZ',
    alpha3: 'BLZ',
    dial: '501',
  },
  {
    name: 'Benin',
    numeric: '204',
    alpha2: 'BJ',
    alpha3: 'BEN',
    dial: '229',
  },
  {
    name: 'Bermuda',
    numeric: '060',
    alpha2: 'BM',
    alpha3: 'BMU',
    dial: '1441',
  },
  {
    name: 'Bhutan',
    numeric: '064',
    alpha2: 'BT',
    alpha3: 'BTN',
    dial: '975',
  },
  {
    name: 'Bolivia (Plurinational State of)',
    numeric: '068',
    alpha2: 'BO',
    alpha3: 'BOL',
    dial: '591',
  },
  {
    name: 'Bonaire, Sint Eustatius and Saba[a]',
    numeric: '535',
    alpha2: 'BQ',
    alpha3: 'BES',
    dial: '599',
  },
  {
    name: 'Bosnia and Herzegovina',
    numeric: '070',
    alpha2: 'BA',
    alpha3: 'BIH',
    dial: '387',
  },
  {
    name: 'Botswana',
    numeric: '072',
    alpha2: 'BW',
    alpha3: 'BWA',
    dial: '267',
  },
  {
    name: 'Bouvet Island',
    numeric: '074',
    alpha2: 'BV',
    alpha3: 'BVT',
    dial: '47',
  },
  {
    name: 'Brazil',
    numeric: '076',
    alpha2: 'BR',
    alpha3: 'BRA',
    dial: '55',
  },
  {
    name: 'British Indian Ocean Territory',
    numeric: '086',
    alpha2: 'IO',
    alpha3: 'IOT',
    dial: '246',
  },
  {
    name: 'Brunei Darussalam',
    numeric: '096',
    alpha2: 'BN',
    alpha3: 'BRN',
    dial: '673',
  },
  {
    name: 'Bulgaria',
    numeric: '100',
    alpha2: 'BG',
    alpha3: 'BGR',
    dial: '359',
  },
  {
    name: 'Burkina Faso',
    numeric: '854',
    alpha2: 'BF',
    alpha3: 'BFA',
    dial: '226',
  },
  {
    name: 'Burundi',
    numeric: '108',
    alpha2: 'BI',
    alpha3: 'BDI',
    dial: '257',
  },
  {
    name: 'Cabo Verde',
    numeric: '132',
    alpha2: 'CV',
    alpha3: 'CPV',
    dial: '238',
  },
  {
    name: 'Cambodia',
    numeric: '116',
    alpha2: 'KH',
    alpha3: 'KHM',
    dial: '855',
  },
  {
    name: 'Cameroon',
    numeric: '120',
    alpha2: 'CM',
    alpha3: 'CMR',
    dial: '237',
  },
  {
    name: 'Canada',
    numeric: '124',
    alpha2: 'CA',
    alpha3: 'CAN',
    dial: '1',
  },
  {
    name: 'Cayman Islands',
    numeric: '136',
    alpha2: 'KY',
    alpha3: 'CYM',
    dial: '1345',
  },
  {
    name: 'Central African Republic',
    numeric: '140',
    alpha2: 'CF',
    alpha3: 'CAF',
    dial: '236',
  },
  {
    name: 'Chad',
    numeric: '148',
    alpha2: 'TD',
    alpha3: 'TCD',
    dial: '235',
  },
  {
    name: 'Chile',
    numeric: '152',
    alpha2: 'CL',
    alpha3: 'CHL',
    dial: '56',
  },
  {
    name: 'China',
    numeric: '156',
    alpha2: 'CN',
    alpha3: 'CHN',
    dial: '86',
  },
  {
    name: 'Christmas Island',
    numeric: '162',
    alpha2: 'CX',
    alpha3: 'CXR',
    dial: '61',
  },
  {
    name: 'Cocos (Keeling) Islands',
    numeric: '166',
    alpha2: 'CC',
    alpha3: 'CCK',
    dial: '61',
  },
  {
    name: 'Colombia',
    numeric: '170',
    alpha2: 'CO',
    alpha3: 'COL',
    dial: '57',
  },
  {
    name: 'Comoros',
    numeric: '174',
    alpha2: 'KM',
    alpha3: 'COM',
    dial: '269',
  },
  {
    name: 'Congo',
    numeric: '178',
    alpha2: 'CG',
    alpha3: 'COG',
    dial: '242',
  },
  {
    name: 'Congo, Democratic Republic of the',
    numeric: '180',
    alpha2: 'CD',
    alpha3: 'COD',
    dial: '243',
  },
  {
    name: 'Cook Islands',
    numeric: '184',
    alpha2: 'CK',
    alpha3: 'COK',
    dial: '682',
  },
  {
    name: 'Costa Rica',
    numeric: '188',
    alpha2: 'CR',
    alpha3: 'CRI',
    dial: '506',
  },
  {
    name: "Côte d'Ivoire",
    numeric: '384',
    alpha2: 'CI',
    alpha3: 'CIV',
    dial: '225',
  },
  {
    name: 'Croatia',
    numeric: '191',
    alpha2: 'HR',
    alpha3: 'HRV',
    dial: '385',
  },
  {
    name: 'Cuba',
    numeric: '192',
    alpha2: 'CU',
    alpha3: 'CUB',
    dial: '53',
  },
  {
    name: 'Curaçao',
    numeric: '531',
    alpha2: 'CW',
    alpha3: 'CUW',
    dial: '599',
  },
  {
    name: 'Cyprus',
    numeric: '196',
    alpha2: 'CY',
    alpha3: 'CYP',
    dial: '357',
  },
  {
    name: 'Czechia',
    numeric: '203',
    alpha2: 'CZ',
    alpha3: 'CZE',
    dial: '420',
  },
  {
    name: 'Denmark',
    numeric: '208',
    alpha2: 'DK',
    alpha3: 'DNK',
    dial: '45',
  },
  {
    name: 'Djibouti',
    numeric: '262',
    alpha2: 'DJ',
    alpha3: 'DJI',
    dial: '253',
  },
  {
    name: 'Dominica',
    numeric: '212',
    alpha2: 'DM',
    alpha3: 'DMA',
    dial: '1767',
  },
  {
    name: 'Dominican Republic',
    numeric: '214',
    alpha2: 'DO',
    alpha3: 'DOM',
    dial: '1809',
  },
  {
    name: 'Ecuador',
    numeric: '218',
    alpha2: 'EC',
    alpha3: 'ECU',
    dial: '593',
  },
  {
    name: 'Egypt',
    numeric: '818',
    alpha2: 'EG',
    alpha3: 'EGY',
    dial: '20',
  },
  {
    name: 'El Salvador',
    numeric: '222',
    alpha2: 'SV',
    alpha3: 'SLV',
    dial: '503',
  },
  {
    name: 'Equatorial Guinea',
    numeric: '226',
    alpha2: 'GQ',
    alpha3: 'GNQ',
    dial: '240',
  },
  {
    name: 'Eritrea',
    numeric: '232',
    alpha2: 'ER',
    alpha3: 'ERI',
    dial: '291',
  },
  {
    name: 'Estonia',
    numeric: '233',
    alpha2: 'EE',
    alpha3: 'EST',
    dial: '372',
  },
  {
    name: 'Eswatini',
    numeric: '748',
    alpha2: 'SZ',
    alpha3: 'SWZ',
    dial: '268',
  },
  {
    name: 'Ethiopia',
    numeric: '231',
    alpha2: 'ET',
    alpha3: 'ETH',
    dial: '251',
  },
  {
    name: 'Falkland Islands (Malvinas)',
    numeric: '238',
    alpha2: 'FK',
    alpha3: 'FLK',
    dial: '500',
  },
  {
    name: 'Faroe Islands',
    numeric: '234',
    alpha2: 'FO',
    alpha3: 'FRO',
    dial: '298',
  },
  {
    name: 'Fiji',
    numeric: '242',
    alpha2: 'FJ',
    alpha3: 'FJI',
    dial: '679',
  },
  {
    name: 'Finland',
    numeric: '246',
    alpha2: 'FI',
    alpha3: 'FIN',
    dial: '358',
  },
  {
    name: 'France',
    numeric: '250',
    alpha2: 'FR',
    alpha3: 'FRA',
    dial: '33',
  },
  {
    name: 'French Guiana',
    numeric: '254',
    alpha2: 'GF',
    alpha3: 'GUF',
    dial: '44',
  },
  {
    name: 'French Polynesia',
    numeric: '258',
    alpha2: 'PF',
    alpha3: 'PYF',
    dial: '689',
  },
  {
    name: 'French Southern Territories',
    numeric: '260',
    alpha2: 'TF',
    alpha3: 'ATF',
    dial: '262',
  },
  {
    name: 'Gabon',
    numeric: '266',
    alpha2: 'GA',
    alpha3: 'GAB',
    dial: '44',
  },
  {
    name: 'Gambia',
    numeric: '270',
    alpha2: 'GM',
    alpha3: 'GMB',
    dial: '220',
  },
  {
    name: 'Georgia',
    numeric: '268',
    alpha2: 'GE',
    alpha3: 'GEO',
    dial: '594',
  },
  {
    name: 'Germany',
    numeric: '276',
    alpha2: 'DE',
    alpha3: 'DEU',
    dial: '49',
  },
  {
    name: 'Ghana',
    numeric: '288',
    alpha2: 'GH',
    alpha3: 'GHA',
    dial: '233',
  },
  {
    name: 'Gibraltar',
    numeric: '292',
    alpha2: 'GI',
    alpha3: 'GIB',
    dial: '350',
  },
  {
    name: 'Greece',
    numeric: '300',
    alpha2: 'GR',
    alpha3: 'GRC',
    dial: '30',
  },
  {
    name: 'Greenland',
    numeric: '304',
    alpha2: 'GL',
    alpha3: 'GRL',
    dial: '299',
  },
  {
    name: 'Grenada',
    numeric: '308',
    alpha2: 'GD',
    alpha3: 'GRD',
    dial: '995',
  },
  {
    name: 'Guadeloupe',
    numeric: '312',
    alpha2: 'GP',
    alpha3: 'GLP',
    dial: '590',
  },
  {
    name: 'Guam',
    numeric: '316',
    alpha2: 'GU',
    alpha3: 'GUM',
    dial: '1671',
  },
  {
    name: 'Guatemala',
    numeric: '320',
    alpha2: 'GT',
    alpha3: 'GTM',
    dial: '502',
  },
  {
    name: 'Guernsey',
    numeric: '831',
    alpha2: 'GG',
    alpha3: 'GGY',
    dial: '44',
  },
  {
    name: 'Guinea',
    numeric: '324',
    alpha2: 'GN',
    alpha3: 'GIN',
    dial: '224',
  },
  {
    name: 'Guinea-Bissau',
    numeric: '624',
    alpha2: 'GW',
    alpha3: 'GNB',
    dial: '245',
  },
  {
    name: 'Guyana',
    numeric: '328',
    alpha2: 'GY',
    alpha3: 'GUY',
    dial: '592',
  },
  {
    name: 'Haiti',
    numeric: '332',
    alpha2: 'HT',
    alpha3: 'HTI',
    dial: '509',
  },
  {
    name: 'Heard Island and McDonald Islands',
    numeric: '334',
    alpha2: 'HM',
    alpha3: 'HMD',
    dial: '672',
  },
  {
    name: 'Holy See',
    numeric: '336',
    alpha2: 'VA',
    alpha3: 'VAT',
    dial: '379',
  },
  {
    name: 'Honduras',
    numeric: '340',
    alpha2: 'HN',
    alpha3: 'HND',
    dial: '504',
  },
  {
    name: 'Hong Kong',
    numeric: '344',
    alpha2: 'HK',
    alpha3: 'HKG',
    dial: '852',
  },
  {
    name: 'Hungary',
    numeric: '348',
    alpha2: 'HU',
    alpha3: 'HUN',
    dial: '36',
  },
  {
    name: 'Iceland',
    numeric: '352',
    alpha2: 'IS',
    alpha3: 'ISL',
    dial: '354',
  },
  {
    name: 'India',
    numeric: '356',
    alpha2: 'IN',
    alpha3: 'IND',
    dial: '91',
  },
  {
    name: 'Indonesia',
    numeric: '360',
    alpha2: 'ID',
    alpha3: 'IDN',
    dial: '62',
  },
  {
    name: 'Iran (Islamic Republic of)',
    numeric: '364',
    alpha2: 'IR',
    alpha3: 'IRN',
    dial: '98',
  },
  {
    name: 'Iraq',
    numeric: '368',
    alpha2: 'IQ',
    alpha3: 'IRQ',
    dial: '964',
  },
  {
    name: 'Ireland',
    numeric: '372',
    alpha2: 'IE',
    alpha3: 'IRL',
    dial: '353',
  },
  {
    name: 'Isle of Man',
    numeric: '833',
    alpha2: 'IM',
    alpha3: 'IMN',
    dial: '44',
  },
  {
    name: 'Israel',
    numeric: '376',
    alpha2: 'IL',
    alpha3: 'ISR',
    dial: '972',
  },
  {
    name: 'Italy',
    numeric: '380',
    alpha2: 'IT',
    alpha3: 'ITA',
    dial: '39',
  },
  {
    name: 'Jamaica',
    numeric: '388',
    alpha2: 'JM',
    alpha3: 'JAM',
    dial: '1876',
  },
  {
    name: 'Japan',
    numeric: '392',
    alpha2: 'JP',
    alpha3: 'JPN',
    dial: '81',
  },
  {
    name: 'Jersey',
    numeric: '832',
    alpha2: 'JE',
    alpha3: 'JEY',
    dial: '44',
  },
  {
    name: 'Jordan',
    numeric: '400',
    alpha2: 'JO',
    alpha3: 'JOR',
    dial: '962',
  },
  {
    name: 'Kazakhstan',
    numeric: '398',
    alpha2: 'KZ',
    alpha3: 'KAZ',
    dial: '7',
  },
  {
    name: 'Kenya',
    numeric: '404',
    alpha2: 'KE',
    alpha3: 'KEN',
    dial: '254',
  },
  {
    name: 'Kiribati',
    numeric: '296',
    alpha2: 'KI',
    alpha3: 'KIR',
    dial: '686',
  },
  {
    name: "Korea (Democratic People's Republic of)",
    numeric: '408',
    alpha2: 'KP',
    alpha3: 'PRK',
    dial: '850',
  },
  {
    name: 'Korea, Republic of',
    numeric: '410',
    alpha2: 'KR',
    alpha3: 'KOR',
    dial: '82',
  },
  {
    name: 'Kuwait',
    numeric: '414',
    alpha2: 'KW',
    alpha3: 'KWT',
    dial: '965',
  },
  {
    name: 'Kyrgyzstan',
    numeric: '417',
    alpha2: 'KG',
    alpha3: 'KGZ',
    dial: '996',
  },
  {
    name: "Lao People's Democratic Republic",
    numeric: '418',
    alpha2: 'LA',
    alpha3: 'LAO',
    dial: '856',
  },
  {
    name: 'Latvia',
    numeric: '428',
    alpha2: 'LV',
    alpha3: 'LVA',
    dial: '371',
  },
  {
    name: 'Lebanon',
    numeric: '422',
    alpha2: 'LB',
    alpha3: 'LBN',
    dial: '961',
  },
  {
    name: 'Lesotho',
    numeric: '426',
    alpha2: 'LS',
    alpha3: 'LSO',
    dial: '266',
  },
  {
    name: 'Liberia',
    numeric: '430',
    alpha2: 'LR',
    alpha3: 'LBR',
    dial: '231',
  },
  {
    name: 'Libya',
    numeric: '434',
    alpha2: 'LY',
    alpha3: 'LBY',
    dial: '218',
  },
  {
    name: 'Liechtenstein',
    numeric: '438',
    alpha2: 'LI',
    alpha3: 'LIE',
    dial: '423',
  },
  {
    name: 'Lithuania',
    numeric: '440',
    alpha2: 'LT',
    alpha3: 'LTU',
    dial: '370',
  },
  {
    name: 'Luxembourg',
    numeric: '442',
    alpha2: 'LU',
    alpha3: 'LUX',
    dial: '352',
  },
  {
    name: 'Macao',
    numeric: '446',
    alpha2: 'MO',
    alpha3: 'MAC',
    dial: '853',
  },
  {
    name: 'Madagascar',
    numeric: '450',
    alpha2: 'MG',
    alpha3: 'MDG',
    dial: '261',
  },
  {
    name: 'Malawi',
    numeric: '454',
    alpha2: 'MW',
    alpha3: 'MWI',
    dial: '265',
  },
  {
    name: 'Malaysia',
    numeric: '458',
    alpha2: 'MY',
    alpha3: 'MYS',
    dial: '60',
  },
  {
    name: 'Maldives',
    numeric: '462',
    alpha2: 'MV',
    alpha3: 'MDV',
    dial: '960',
  },
  {
    name: 'Mali',
    numeric: '466',
    alpha2: 'ML',
    alpha3: 'MLI',
    dial: '223',
  },
  {
    name: 'Malta',
    numeric: '470',
    alpha2: 'MT',
    alpha3: 'MLT',
    dial: '356',
  },
  {
    name: 'Marshall Islands',
    numeric: '584',
    alpha2: 'MH',
    alpha3: 'MHL',
    dial: '692',
  },
  {
    name: 'Martinique',
    numeric: '474',
    alpha2: 'MQ',
    alpha3: 'MTQ',
    dial: '596',
  },
  {
    name: 'Mauritania',
    numeric: '478',
    alpha2: 'MR',
    alpha3: 'MRT',
    dial: '222',
  },
  {
    name: 'Mauritius',
    numeric: '480',
    alpha2: 'MU',
    alpha3: 'MUS',
    dial: '230',
  },
  {
    name: 'Mayotte',
    numeric: '175',
    alpha2: 'YT',
    alpha3: 'MYT',
    dial: '262',
  },
  {
    name: 'Mexico',
    numeric: '484',
    alpha2: 'MX',
    alpha3: 'MEX',
    dial: '52',
  },
  {
    name: 'Micronesia (Federated States of)',
    numeric: '583',
    alpha2: 'FM',
    alpha3: 'FSM',
    dial: '691',
  },
  {
    name: 'Moldova, Republic of',
    numeric: '498',
    alpha2: 'MD',
    alpha3: 'MDA',
    dial: '373',
  },
  {
    name: 'Monaco',
    numeric: '492',
    alpha2: 'MC',
    alpha3: 'MCO',
    dial: '377',
  },
  {
    name: 'Mongolia',
    numeric: '496',
    alpha2: 'MN',
    alpha3: 'MNG',
    dial: '976',
  },
  {
    name: 'Montenegro',
    numeric: '499',
    alpha2: 'ME',
    alpha3: 'MNE',
    dial: '382',
  },
  {
    name: 'Montserrat',
    numeric: '500',
    alpha2: 'MS',
    alpha3: 'MSR',
    dial: '1664',
  },
  {
    name: 'Morocco',
    numeric: '504',
    alpha2: 'MA',
    alpha3: 'MAR',
    dial: '212',
  },
  {
    name: 'Mozambique',
    numeric: '508',
    alpha2: 'MZ',
    alpha3: 'MOZ',
    dial: '258',
  },
  {
    name: 'Myanmar',
    numeric: '104',
    alpha2: 'MM',
    alpha3: 'MMR',
    dial: '95',
  },
  {
    name: 'Namibia',
    numeric: '516',
    alpha2: 'NA',
    alpha3: 'NAM',
    dial: '264',
  },
  {
    name: 'Nauru',
    numeric: '520',
    alpha2: 'NR',
    alpha3: 'NRU',
    dial: '674',
  },
  {
    name: 'Nepal',
    numeric: '524',
    alpha2: 'NP',
    alpha3: 'NPL',
    dial: '977',
  },
  {
    name: 'Netherlands',
    numeric: '528',
    alpha2: 'NL',
    alpha3: 'NLD',
    dial: '31',
  },
  {
    name: 'New Caledonia',
    numeric: '540',
    alpha2: 'NC',
    alpha3: 'NCL',
    dial: '687',
  },
  {
    name: 'New Zealand',
    numeric: '554',
    alpha2: 'NZ',
    alpha3: 'NZL',
    dial: '64',
  },
  {
    name: 'Nicaragua',
    numeric: '558',
    alpha2: 'NI',
    alpha3: 'NIC',
    dial: '505',
  },
  {
    name: 'Niger',
    numeric: '562',
    alpha2: 'NE',
    alpha3: 'NER',
    dial: '227',
  },
  {
    name: 'Nigeria',
    numeric: '566',
    alpha2: 'NG',
    alpha3: 'NGA',
    dial: '234',
  },
  {
    name: 'Niue',
    numeric: '570',
    alpha2: 'NU',
    alpha3: 'NIU',
    dial: '683',
  },
  {
    name: 'Norfolk Island',
    numeric: '574',
    alpha2: 'NF',
    alpha3: 'NFK',
    dial: '672',
  },
  {
    name: 'North Macedonia',
    numeric: '807',
    alpha2: 'MK',
    alpha3: 'MKD',
    dial: '389',
  },
  {
    name: 'Northern Mariana Islands',
    numeric: '580',
    alpha2: 'MP',
    alpha3: 'MNP',
    dial: '1670',
  },
  {
    name: 'Norway',
    numeric: '578',
    alpha2: 'NO',
    alpha3: 'NOR',
    dial: '47',
  },
  {
    name: 'Oman',
    numeric: '512',
    alpha2: 'OM',
    alpha3: 'OMN',
    dial: '968',
  },
  {
    name: 'Pakistan',
    numeric: '586',
    alpha2: 'PK',
    alpha3: 'PAK',
    dial: '92',
  },
  {
    name: 'Palau',
    numeric: '585',
    alpha2: 'PW',
    alpha3: 'PLW',
    dial: '680',
  },
  {
    name: 'Palestine, State of',
    numeric: '275',
    alpha2: 'PS',
    alpha3: 'PSE',
    dial: '970',
  },
  {
    name: 'Panama',
    numeric: '591',
    alpha2: 'PA',
    alpha3: 'PAN',
    dial: '507',
  },
  {
    name: 'Papua New Guinea',
    numeric: '598',
    alpha2: 'PG',
    alpha3: 'PNG',
    dial: '675',
  },
  {
    name: 'Paraguay',
    numeric: '600',
    alpha2: 'PY',
    alpha3: 'PRY',
    dial: '595',
  },
  {
    name: 'Peru',
    numeric: '604',
    alpha2: 'PE',
    alpha3: 'PER',
    dial: '51',
  },
  {
    name: 'Philippines',
    numeric: '608',
    alpha2: 'PH',
    alpha3: 'PHL',
    dial: '63',
  },
  {
    name: 'Pitcairn',
    numeric: '612',
    alpha2: 'PN',
    alpha3: 'PCN',
    dial: '64',
  },
  {
    name: 'Poland',
    numeric: '616',
    alpha2: 'PL',
    alpha3: 'POL',
    dial: '48',
  },
  {
    name: 'Portugal',
    numeric: '620',
    alpha2: 'PT',
    alpha3: 'PRT',
    dial: '351',
  },
  {
    name: 'Puerto Rico',
    numeric: '630',
    alpha2: 'PR',
    alpha3: 'PRI',
    dial: '1787',
  },
  {
    name: 'Qatar',
    numeric: '634',
    alpha2: 'QA',
    alpha3: 'QAT',
    dial: '974',
  },
  {
    name: 'Réunion',
    numeric: '638',
    alpha2: 'RE',
    alpha3: 'REU',
    dial: '262',
  },
  {
    name: 'Romania',
    numeric: '642',
    alpha2: 'RO',
    alpha3: 'ROU',
    dial: '40',
  },
  {
    name: 'Russian Federation',
    numeric: '643',
    alpha2: 'RU',
    alpha3: 'RUS',
    dial: '7',
  },
  {
    name: 'Rwanda',
    numeric: '646',
    alpha2: 'RW',
    alpha3: 'RWA',
    dial: '250',
  },
  {
    name: 'Saint Barthélemy',
    numeric: '652',
    alpha2: 'BL',
    alpha3: 'BLM',
    dial: '590',
  },
  {
    name: 'Saint Helena, Ascension and Tristan da Cunha[b]',
    numeric: '654',
    alpha2: 'SH',
    alpha3: 'SHN',
    dial: '290',
  },
  {
    name: 'Saint Kitts and Nevis',
    numeric: '659',
    alpha2: 'KN',
    alpha3: 'KNA',
    dial: '1869',
  },
  {
    name: 'Saint Lucia',
    numeric: '662',
    alpha2: 'LC',
    alpha3: 'LCA',
    dial: '1758',
  },
  {
    name: 'Saint Martin (French part)',
    numeric: '663',
    alpha2: 'MF',
    alpha3: 'MAF',
    dial: '590',
  },
  {
    name: 'Saint Pierre and Miquelon',
    numeric: '666',
    alpha2: 'PM',
    alpha3: 'SPM',
    dial: '508',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    numeric: '670',
    alpha2: 'VC',
    alpha3: 'VCT',
    dial: '1784',
  },
  {
    name: 'Samoa',
    numeric: '882',
    alpha2: 'WS',
    alpha3: 'WSM',
    dial: '685',
  },
  {
    name: 'San Marino',
    numeric: '674',
    alpha2: 'SM',
    alpha3: 'SMR',
    dial: '378',
  },
  {
    name: 'Sao Tome and Principe',
    numeric: '678',
    alpha2: 'ST',
    alpha3: 'STP',
    dial: '239',
  },
  {
    name: 'Saudi Arabia',
    numeric: '682',
    alpha2: 'SA',
    alpha3: 'SAU',
    dial: '966',
  },
  {
    name: 'Senegal',
    numeric: '686',
    alpha2: 'SN',
    alpha3: 'SEN',
    dial: '221',
  },
  {
    name: 'Serbia',
    numeric: '688',
    alpha2: 'RS',
    alpha3: 'SRB',
    dial: '381',
  },
  {
    name: 'Seychelles',
    numeric: '690',
    alpha2: 'SC',
    alpha3: 'SYC',
    dial: '248',
  },
  {
    name: 'Sierra Leone',
    numeric: '694',
    alpha2: 'SL',
    alpha3: 'SLE',
    dial: '232',
  },
  {
    name: 'Singapore',
    numeric: '702',
    alpha2: 'SG',
    alpha3: 'SGP',
    dial: '65',
  },
  {
    name: 'Sint Maarten (Dutch part)',
    numeric: '534',
    alpha2: 'SX',
    alpha3: 'SXM',
    dial: '1721',
  },
  {
    name: 'Slovakia',
    numeric: '703',
    alpha2: 'SK',
    alpha3: 'SVK',
    dial: '421',
  },
  {
    name: 'Slovenia',
    numeric: '705',
    alpha2: 'SI',
    alpha3: 'SVN',
    dial: '386',
  },
  {
    name: 'Solomon Islands',
    numeric: '090',
    alpha2: 'SB',
    alpha3: 'SLB',
    dial: '677',
  },
  {
    name: 'Somalia',
    numeric: '706',
    alpha2: 'SO',
    alpha3: 'SOM',
    dial: '252',
  },
  {
    name: 'South Africa',
    numeric: '710',
    alpha2: 'ZA',
    alpha3: 'ZAF',
    dial: '27',
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    numeric: '239',
    alpha2: 'GS',
    alpha3: 'SGS',
    dial: '500',
  },
  {
    name: 'South Sudan',
    numeric: '728',
    alpha2: 'SS',
    alpha3: 'SSD',
    dial: '211',
  },
  {
    name: 'Spain',
    numeric: '724',
    alpha2: 'ES',
    alpha3: 'ESP',
    dial: '34',
  },
  {
    name: 'Sri Lanka',
    numeric: '144',
    alpha2: 'LK',
    alpha3: 'LKA',
    dial: '94',
  },
  {
    name: 'Sudan',
    numeric: '729',
    alpha2: 'SD',
    alpha3: 'SDN',
    dial: '249',
  },
  {
    name: 'Suriname',
    numeric: '740',
    alpha2: 'SR',
    alpha3: 'SUR',
    dial: '597',
  },
  {
    name: 'Svalbard and Jan Mayen[c]',
    numeric: '744',
    alpha2: 'SJ',
    alpha3: 'SJM',
    dial: '47',
  },
  {
    name: 'Sweden',
    numeric: '752',
    alpha2: 'SE',
    alpha3: 'SWE',
    dial: '46',
  },
  {
    name: 'Switzerland',
    numeric: '756',
    alpha2: 'CH',
    alpha3: 'CHE',
    dial: '41',
  },
  {
    name: 'Syrian Arab Republic',
    numeric: '760',
    alpha2: 'SY',
    alpha3: 'SYR',
    dial: '963',
  },
  {
    name: 'Taiwan, Province of China',
    numeric: '158',
    alpha2: 'TW',
    alpha3: 'TWN',
    dial: '886',
  },
  {
    name: 'Tajikistan',
    numeric: '762',
    alpha2: 'TJ',
    alpha3: 'TJK',
    dial: '992',
  },
  {
    name: 'Tanzania, United Republic of',
    numeric: '834',
    alpha2: 'TZ',
    alpha3: 'TZA',
    dial: '255',
  },
  {
    name: 'Thailand',
    numeric: '764',
    alpha2: 'TH',
    alpha3: 'THA',
    dial: '66',
  },
  {
    name: 'Timor-Leste',
    numeric: '626',
    alpha2: 'TL',
    alpha3: 'TLS',
    dial: '670',
  },
  {
    name: 'Togo',
    numeric: '768',
    alpha2: 'TG',
    alpha3: 'TGO',
    dial: '228',
  },
  {
    name: 'Tokelau',
    numeric: '772',
    alpha2: 'TK',
    alpha3: 'TKL',
    dial: '690',
  },
  {
    name: 'Tonga',
    numeric: '776',
    alpha2: 'TO',
    alpha3: 'TON',
    dial: '676',
  },
  {
    name: 'Trinidad and Tobago',
    numeric: '780',
    alpha2: 'TT',
    alpha3: 'TTO',
    dial: '1868',
  },
  {
    name: 'Tunisia',
    numeric: '788',
    alpha2: 'TN',
    alpha3: 'TUN',
    dial: '216',
  },
  {
    name: 'Turkey',
    numeric: '792',
    alpha2: 'TR',
    alpha3: 'TUR',
    dial: '90',
  },
  {
    name: 'Turkmenistan',
    numeric: '795',
    alpha2: 'TM',
    alpha3: 'TKM',
    dial: '993',
  },
  {
    name: 'Turks and Caicos Islands',
    numeric: '796',
    alpha2: 'TC',
    alpha3: 'TCA',
    dial: '1649',
  },
  {
    name: 'Tuvalu',
    numeric: '798',
    alpha2: 'TV',
    alpha3: 'TUV',
    dial: '688',
  },
  {
    name: 'Uganda',
    numeric: '800',
    alpha2: 'UG',
    alpha3: 'UGA',
    dial: '256',
  },
  {
    name: 'Ukraine',
    numeric: '804',
    alpha2: 'UA',
    alpha3: 'UKR',
    dial: '380',
  },
  {
    name: 'United Arab Emirates',
    numeric: '784',
    alpha2: 'AE',
    alpha3: 'ARE',
    dial: '971',
  },
  {
    name: 'United Kingdom of Great Britain and Northern Ireland',
    numeric: '826',
    alpha2: 'GB',
    alpha3: 'GBR',
    dial: '1473',
  },
  {
    name: 'United States of America',
    numeric: '840',
    alpha2: 'US',
    alpha3: 'USA',
    dial: '1',
  },
  {
    name: 'United States Minor Outlying Islands[e]',
    numeric: '581',
    alpha2: 'UM',
    alpha3: 'UMI',
    dial: '246',
  },
  {
    name: 'Uruguay',
    numeric: '858',
    alpha2: 'UY',
    alpha3: 'URY',
    dial: '598',
  },
  {
    name: 'Uzbekistan',
    numeric: '860',
    alpha2: 'UZ',
    alpha3: 'UZB',
    dial: '998',
  },
  {
    name: 'Vanuatu',
    numeric: '548',
    alpha2: 'VU',
    alpha3: 'VUT',
    dial: '678',
  },
  {
    name: 'Venezuela (Bolivarian Republic of)',
    numeric: '862',
    alpha2: 'VE',
    alpha3: 'VEN',
    dial: '58',
  },
  {
    name: 'Viet Nam',
    numeric: '704',
    alpha2: 'VN',
    alpha3: 'VNM',
    dial: '84',
  },
  {
    name: 'Virgin Islands (British)',
    numeric: '092',
    alpha2: 'VG',
    alpha3: 'VGB',
    dial: '1284',
  },
  {
    name: 'Virgin Islands (U.S.)',
    numeric: '850',
    alpha2: 'VI',
    alpha3: 'VIR',
    dial: '1340',
  },
  {
    name: 'Wallis and Futuna',
    numeric: '876',
    alpha2: 'WF',
    alpha3: 'WLF',
    dial: '681',
  },
  {
    name: 'Western Sahara',
    numeric: '732',
    alpha2: 'EH',
    alpha3: 'ESH',
    dial: '212',
  },
  {
    name: 'Yemen',
    numeric: '887',
    alpha2: 'YE',
    alpha3: 'YEM',
    dial: '967',
  },
  {
    name: 'Zambia',
    numeric: '894',
    alpha2: 'ZM',
    alpha3: 'ZMB',
    dial: '260',
  },
  {
    name: 'Zimbabwe',
    numeric: '716',
    alpha2: 'ZW',
    alpha3: 'ZWE',
    dial: '263',
  },
];
